packages:
  - contracts
  - agent
  - uniswap

allowBuilds:
  bufferutil: true
  es5-ext: set this to true or false
  esbuild: set this to true or false
  keccak: true
  secp256k1: true
  utf-8-validate: set this to true or false
